name = "github-metrics"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "01ccc7704e3d44e8bf8e5e1c3049274b"
preview_id = "01ccc7704e3d44e8bf8e5e1c3049274b"
